name: Java 8 Build

on: [push, pull_request]

jobs:
  java-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: ['core', 'lib', 'tests', 'misc']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and test
        run: ./tools/ci/java_test_controller.sh "${{ matrix.stage }}"
      - name: Repeat LogisticRegressionTest until failure
        run: cd flink-ml-lib && bash ../tools/ci/run_until_fail.sh org.apache.flink.ml.classification.LogisticRegressionTest
